### ISSUE TITLE
немного текста new bulk7 - Handle いろはにほへと`~@#$%^&*()_+|-=\{}[]:”;’<>?,./®©£¥¢¦§«»€ немного текста &quot; &apos; &amp; &lt; &gt javascript:alert(‘1’); 

### ISSUE THREAD

**Issue by anna04test** [Org4/AnotherOrgRepo#27]

**Comment by status-open-bounty** [comment]
Current balance: 0.056 ETH
Contract address: [0xbd3eb23033d2d63b2753f98da27f0e45d9b1591b](https://ropsten.etherscan.io/address/0xbd3eb23033d2d63b2753f98da27f0e45d9b1591b)
![QR Code](https://testing.openbounty.status.im/qr/Org4/AnotherOrgRepo/bounty/27/9cdd98f10fd3fcc357903390d3ba697c5b916a8aae4fa4480db4d1a02b1879e9/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://testing.openbounty.status.im](https://testing.openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
